### ISSUE TITLE
Use class for styling elements

### ISSUE THREAD

**Issue by cyouh95** [ARB89/prj-rev-bwfs-dasmoto#3]
Alternatively, you could add a class to the `strong` elements and use that as the selector to style those price text. That way, in case you want to use the `strong` tag for another part of your page later, they won't all automatically be styled blue, for example.

HTML:
```html
<p> ... <strong class="price">Starting at $3.00 / brush.</strong></p>
```

CSS:
```css
.price {
  font-family: Helvetica;
  font-weight: bold;
  color:blue;
}
```

https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/index.html#L27
https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/recursos/style.css#L7-L11
